pipeline {
    agent any
    stages {
        stage('SCM Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CleanBeforeCheckout', deleteUntrackedNestedRepositories: true]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'github-login', url: 'https://github.com/Yuzyzy88/trial-devsecops.git']]])
            }
        }
        stage('Create Image') {
            steps {
                sh '''
                docker image rm sulistiowatiayu/devsecops:v1 || echo "No existing image found"
                docker compose -f app/deploy/docker-compose.yaml build --no-cache

                '''
            }
        }
        stage('Push Image') {
            steps {
                sh '''
                set +x
                docker login --username=sulistiowatiayu --password=$dockerPassword
                set -x
                docker push sulistiowatiayu/devsecops:v1
                '''
            }
        }
        stage('Run the docker compose') {
            steps {
                sh '''
                docker compose -f app/deploy/docker-compose.yaml stop -d
                docker compose -f app/deploy/docker-compose.yaml up -d
                '''
            }
        }
    }
}
