pipeline {
    agent any
    stages {


        // stage('SCM Checkout') {
        //     steps {
        //         checkout([$class: 'GitSCM', branches: [[name: '*/main']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CleanBeforeCheckout', deleteUntrackedNestedRepositories: true]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'github-login', url: 'https://github.com/Yuzyzy88/trial-devsecops.git']]])
        //     }
        // }

        
        stage('Create Image') {
            steps {
                sh '''
                docker image rm 10.8.60.126:5000/devsecops:v${BUILD_NUMBER} || echo "No existing image found"
                docker-compose -f app/deploy/docker-compose.yaml build --no-cache
                '''
            }
        }

        stage("Misconfig Scanner"){
            steps{
                sh '''
                cd app/
                mkdir /var/www/html/trivy/pipeline${BUILD_NUMBER}/
                touch /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportconfig.html
                trivy config . --format template --template "@deploy/html.tpl" -o /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportconfig.html --severity HIGH,CRITICAL
                '''
            }
        }

         stage("Filesystem Scanner"){
            steps{
                sh '''
                cd app/
                touch /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportfilesystem.html
                trivy fs . --format template --template "@deploy/html.tpl" -o /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportfilesystem.html --severity HIGH,CRITICAL
                '''
            }
        }

        stage("Vulnerability and Secret Scanner"){
            steps{
                sh '''
                cd app/deploy
                touch /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportimagesecretpython.html
                trivy image --format template --template "@html.tpl" -o /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportimagesecretpython.html --severity HIGH,CRITICAL 10.8.60.126:5000/devsecops:v${BUILD_NUMBER}
                
                touch /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportimagesecretdb.html
                trivy image --format template --template "@html.tpl" -o /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportimagesecretdb.html --severity HIGH,CRITICAL mariadb:10.6.3
                '''
            }
        }

        stage('Push Image to nexus') {
            steps {
                sh '''
                set +x
                docker login --username=admin --password=$nexusPassword 10.8.60.126:5000
                set -x
                docker push 10.8.60.126:5000/devsecops:v${BUILD_NUMBER}
                '''
            }
        }
        stage('Run the docker compose') {
            steps {
                sh '''
                docker-compose -f app/deploy/docker-compose.yaml stop
                docker-compose -f app/deploy/docker-compose.yaml up -d
                '''
            }
        }
    }
}
