pipeline {
    agent any
    stages {

        //trivy config . --format template --template "@deploy/html.tpl" -o /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportconfig.html --severity HIGH,CRITICAL
        // check docker file
        stage("Misconfig Scanner"){
            steps{
                sh'trivy'
                sh '''
                whoami
                cd app/
                mkdir /var/www/html/trivy/pipeline${BUILD_NUMBER}/
                touch /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportconfig.html
                '''
            } 
        }

        // scan keamanan dependency yang dibutuhkan docker file
         stage("Filesystem Scanner"){
            steps{
                sh '''
                cd app/
                touch /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportfilesystem.html
                trivy fs . --format template --template "@deploy/html.tpl" -o /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportfilesystem.html --ignore-unfixed --severity HIGH,CRITICAL
                '''
            }
        }

        stage('Create Image') {
            steps {
                sh '''
                docker image rm 10.8.60.126:5000/devsecops:v${BUILD_NUMBER} || echo "No existing image found"
                docker-compose -f app/deploy/docker-compose.yaml build --no-cache
                '''
            }
        }

        

        // scan image
        stage("Vulnerability and Secret Scanner"){
            steps{
                sh '''
                cd app/deploy
                touch /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportimagesecretpython.html
                trivy image --format template --template "@html.tpl" -o /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportimagesecretpython.html --ignore-unfixed --severity HIGH,CRITICAL 10.8.60.126:5000/devsecops:v${BUILD_NUMBER} 
                
                touch /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportimagesecretdb.html
                trivy image --format template --template "@html.tpl" -o /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportimagesecretdb.html --ignore-unfixed --severity HIGH,CRITICAL mariadb:10.6.3
                '''
            }
        }

        stage('Push Image to nexus') {
            steps {
                sh '''
                set +x
                docker login --username=admin --password=$nexusPassword 10.8.60.126:5000
                set -x
                docker push 10.8.60.126:5000/devsecops:v${BUILD_NUMBER}
                '''
            }
        }
        stage('Run the docker compose') {
            steps {
                sh '''
                docker-compose -f app/deploy/docker-compose.yaml stop
                docker-compose -f app/deploy/docker-compose.yaml up -d
                '''
            }
        }
    }
}
